# Change these first
owner: hannesWeb # Your GitHub organization or usernam e, where this repository lives
repo: uptimecheck # The name of this repository

sites:
  - name: Main Webpage
    url: https://www.hannes-hirsch.de
    __dangerous__body_down: "Wir werden bald zurück sein!"
 
  - name: Fallback
    url: http://www.hannes-hirsch.de
    __dangerous__insecure: true

  - name: API
    url: https://hannes-hirsch.de/api
    __dangerous__body_degraded_if_text_missing: "API-Schnittstelle"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.hannes-hirsch.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptimecheck
  theme: ocean
  introTitle: "**Uptimecheck** for Hannes Hirsch's domains."
  introMessage: This is a status page which uses **real-time** data.
  customBodyHtml: >
   <a href="https://www.hannes-hirsch.de" id="floating-button" style="
    display: block;
    width: 120px;
    height: 30px;
    border-radius: 50%;
    background-color: #5C6BC0;
    color: white;
    text-align: center;
    padding: 16px 0;
    position: fixed;
    bottom: 20px;
    right: 20px;
    font-size: 18px;
    text-decoration: none;
    transition: background-color 0.3s;
" onmouseover="this.style.backgroundColor='#3F51B5';" onmouseout="this.style.backgroundColor='#5C6BC0';">
    Zurück
    </a>
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
